GET http://localhost:8080/videos

###

GET http://localhost:8080/videos?limit=10&offset=0

###

POST http://localhost:8080/tags
content-type: application/json

{
    "name": "3"
}
###

POST http://localhost:8080/videos/tags/add
content-type: application/json

{
    "video_ids": [2, 6,7,8],
    "tag_id": 2
}
###

GET http://localhost:8080/tags

###