import VideoView from '@/components/VideoView'

export default function VideoRoute({
  alternatePlayerLabel,
  buildVideoUrl,
  canNext,
  canPrev,
  clearSelection,
  goToLastPage,
  lastPage,
  loading,
  onDeleteVideo,
  onOpenScreenshots,
  onRenameVideo,
  onTagClick,
  onToggleSelectPage,
  openAlternatePlayer,
  openPlayer,
  page,
  randomMode,
  revealFile,
  selectedCount,
  selectedVideoIds,
  setPage,
  setSelectionOpsOpen,
  setTagPickerFor,
  setVideoTempSort,
  toggleSelectVideo,
  videoGlobalSort,
  videoTempSort,
  videos,
  waterfallMode,
  onWaterfallModeChange,
  onLoadMore,
  loadingMore,
  hasMore,
}) {
  return (
    <VideoView
      selectedCount={selectedCount}
      clearSelection={clearSelection}
      setSelectionOpsOpen={setSelectionOpsOpen}
      page={page}
      lastPage={lastPage}
      canPrev={canPrev}
      canNext={canNext}
      loading={loading}
      randomMode={randomMode}
      videoTempSort={videoTempSort}
      videoGlobalSort={videoGlobalSort}
      buildVideoUrl={buildVideoUrl}
      setPage={setPage}
      setVideoTempSort={setVideoTempSort}
      goToLastPage={goToLastPage}
      videos={videos}
      selectedVideoIds={selectedVideoIds}
      toggleSelectVideo={toggleSelectVideo}
      onToggleSelectPage={onToggleSelectPage}
      openPlayer={openPlayer}
      openAlternatePlayer={openAlternatePlayer}
      revealFile={revealFile}
      alternatePlayerLabel={alternatePlayerLabel}
      setTagPickerFor={setTagPickerFor}
      onOpenScreenshots={onOpenScreenshots}
      onRenameVideo={onRenameVideo}
      onDeleteVideo={onDeleteVideo}
      onTagClick={onTagClick}
      waterfallMode={waterfallMode}
      onWaterfallModeChange={onWaterfallModeChange}
      onLoadMore={onLoadMore}
      loadingMore={loadingMore}
      hasMore={hasMore}
    />
  )
}
