import { useEffect, useState } from 'react'
import { Button, CircularProgress } from '@mui/material'
import { postJavCodeInsight } from '@/api'
import { zh } from '@/utils/i18n'

function ChipList({ items }) {
  const rows = Array.isArray(items) ? items.filter(Boolean) : []
  if (!rows.length) return <span className="text-gray-400">—</span>
  return (
    <div className="flex flex-wrap gap-1">
      {rows.map((t) => (
        <span key={t} className="rounded bg-gray-100 px-1.5 py-0.5 text-xs text-gray-800">
          {t}
        </span>
      ))}
    </div>
  )
}

function Field({ label, children }) {
  return (
    <div className="text-sm">
      <div className="text-xs font-semibold text-gray-500">{label}</div>
      <div className="mt-0.5 text-gray-900">{children}</div>
    </div>
  )
}

export default function JavCodeInsightModal({ open, code, onClose }) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [insight, setInsight] = useState(null)

  useEffect(() => {
    if (!open || !String(code || '').trim()) {
      setInsight(null)
      setError('')
      setLoading(false)
      return undefined
    }
    let cancelled = false
    const run = async () => {
      setLoading(true)
      setError('')
      setInsight(null)
      try {
        const resp = await postJavCodeInsight(String(code).trim())
        if (!cancelled) setInsight(resp.insight || null)
      } catch (e) {
        if (!cancelled) setError(e.message || zh('请求失败', 'Request failed'))
      } finally {
        if (!cancelled) setLoading(false)
      }
    }
    void run()
    return () => {
      cancelled = true
    }
  }, [open, code])

  if (!open) return null

  const rating =
    insight?.rating != null && Number.isFinite(Number(insight.rating))
      ? Number(insight.rating).toFixed(1)
      : null

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/40 px-4 py-6">
      <div className="flex max-h-[90vh] w-full max-w-lg flex-col overflow-hidden rounded-lg bg-white shadow-xl">
        <div className="flex items-center justify-between border-b px-4 py-3">
          <div>
            <h2 className="text-base font-semibold">{zh('AI 番号解读', 'AI code insight')}</h2>
            <p className="text-xs text-gray-500">{code}</p>
          </div>
          <button
            type="button"
            className="text-gray-500 hover:text-gray-800"
            onClick={onClose}
            aria-label={zh('关闭', 'Close')}
          >
            ✕
          </button>
        </div>
        <div className="overflow-y-auto px-4 py-3">
          <p className="mb-3 text-xs text-amber-800/90">
            {zh(
              '以下由大模型根据番号推测生成，可能与实际发行信息不符，仅供参考。',
              'Generated by the model from the code only; may be inaccurate.'
            )}
          </p>
          {loading ? (
            <div className="flex items-center justify-center gap-2 py-12 text-sm text-gray-600">
              <CircularProgress size={22} />
              {zh('正在查询…', 'Querying…')}
            </div>
          ) : error ? (
            <p className="text-sm text-red-700">{error}</p>
          ) : insight ? (
            <div className="space-y-3">
              <Field label={zh('中文标题', 'Title (CN)')}>
                {insight.title_cn || insight.title_jp || '—'}
              </Field>
              {insight.title_jp && insight.title_cn !== insight.title_jp ? (
                <Field label={zh('日文标题', 'Title (JP)')}>{insight.title_jp}</Field>
              ) : null}
              <div className="grid grid-cols-2 gap-3">
                <Field label={zh('片商', 'Studio')}>{insight.studio || '—'}</Field>
                <Field label={zh('发行日', 'Release')}>{insight.release_date || '—'}</Field>
                <Field label={zh('时长（分）', 'Duration (min)')}>{insight.duration || '—'}</Field>
                <Field label={zh('评分', 'Rating')}>{rating ?? '—'}</Field>
              </div>
              <Field label={zh('演员', 'Actresses')}>
                <ChipList items={insight.actress} />
              </Field>
              <Field label={zh('类型', 'Genres')}>
                <ChipList items={insight.genres} />
              </Field>
              <Field label={zh('剧情', 'Plot')}>
                <p className="whitespace-pre-wrap leading-relaxed">{insight.plot_summary || '—'}</p>
              </Field>
              <Field label={zh('亮点', 'Highlights')}>
                <ChipList items={insight.highlights} />
              </Field>
              <Field label={zh('不足', 'Weaknesses')}>
                <ChipList items={insight.weaknesses} />
              </Field>
              <Field label={zh('类似番号', 'Similar codes')}>
                <ChipList items={insight.similar_codes} />
              </Field>
              {insight.cover_desc ? (
                <Field label={zh('封面', 'Cover')}>{insight.cover_desc}</Field>
              ) : null}
            </div>
          ) : null}
        </div>
        <div className="flex justify-end border-t px-4 py-3">
          <Button size="small" variant="outlined" onClick={onClose}>
            {zh('关闭', 'Close')}
          </Button>
        </div>
      </div>
    </div>
  )
}
